# Generated by Django 6.0.1 on 2026-01-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userreg_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
